export const productCards = [
  {
    id: 1,
    image: './images/moisturizing-mousse.png',
    skinType: 'для нормальной кожи',
    title: 'Увлажняющий мусс',
    description: 'Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.',
    ingredients: [
      'активные натуральные комплексы',
      'витамины С, А, РР, В И Е',
      'солнцезащитные компоненты',
    ],
    price: 2750,
  },
  {
    id: 2,
    image: './images/moisturizing-mask.png',
    skinType: 'для нормальной кожи',
    title: 'Увлажняющая маска',
    description: 'Способствует удерживанию влаги в верхних слоях кожи.',
    ingredients: ['воски', 'воски', 'масла'],
    price: 3500,
  },
  {
    id: 3,
    image: './images/сleansing-gel.png',
    skinType: 'для нормальной кожи',
    title: 'Гель для умывания',
    description: 'Интенсивно очищает, не повреждает защитный барьер кожи.',
    ingredients: [
      'минералы',
      'витамины С, А, РР, В И Е',
      'солнцезащитные компоненты',
    ],
    price: 1650,
  },
  {
    id: 4,
    image: './images/gift-set-one.png',
    skinType: 'для нормальной кожи',
    title: 'Подарочный набор №1',
    description: 'Набор, состоящий из увлажняющего крема и маски.',
    ingredients: ['воски', 'минералы', 'масла'],
    price: 4750,
  },
  {
    id: 5,
    image: './images/gift-set-five.png',
    skinType: 'для нормальной кожи',
    title: 'Подарочный набор №5',
    description:
      'Весь набор средств Invisible symphony, крем, маска, мусс и гель для умывания.',
    ingredients: ['воски', 'минералы', 'масла'],
    price: 7520,
  },
];
