export const productCards = [
  {
    id: 1,
    price: 2750,
    image: 'moisturizing-mousse',
    skinType: 'для нормальной кожи',
    title: 'Увлажняющий мусс',
    description: 'Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.',
    ingredients: [
      'активные натуральные комплексы',
      'витамины С, А, РР, В И Е',
      'солнцезащитные компоненты',
    ],
  },
  {
    id: 2,
    price: 3500,
    image: 'moisturizing-mask',
    skinType: 'для нормальной кожи',
    title: 'Увлажняющая маска',
    description: 'Способствует удерживанию влаги в верхних слоях кожи.',
    ingredients: ['воски', 'воски', 'масла'],
  },
  {
    id: 3,
    price: 1650,
    image: 'сleansing-gel',
    skinType: 'для нормальной кожи',
    title: 'Гель для умывания',
    description: 'Интенсивно очищает, не повреждает защитный барьер кожи.',
    ingredients: [
      'минералы',
      'витамины С, А, РР, В И Е',
      'солнцезащитные компоненты',
    ],
  },
  {
    id: 4,
    price: 4750,
    image: 'gift-set-one',
    skinType: 'для нормальной кожи',
    title: 'Подарочный набор №1',
    description: 'Набор, состоящий из увлажняющего крема и маски.',
    ingredients: ['воски', 'минералы', 'масла'],
  },
  {
    id: 5,
    price: 7520,
    image: 'gift-set-five',
    skinType: 'для нормальной кожи',
    title: 'Подарочный набор №5',
    description:
      'Весь набор средств Invisible symphony, крем, маска, мусс и гель для умывания.',
    ingredients: ['воски', 'минералы', 'масла'],
  },
];
